name: clica-sso
services:
- name: api
  source_dir: clica-sso-backend
  github:
    repo: rssarti/clica-sso-backend
    branch: main
  build_command: cd clica-sso-backend && npm install && npm run build
  run_command: cd clica-sso-backend && npm run start:prod
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /health
    initial_delay_seconds: 180
    period_seconds: 30
    timeout_seconds: 15
    failure_threshold: 5
    success_threshold: 1
  env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: DB_SSL
    value: "true"
  - key: PGSSLMODE
    value: "require"
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_USERNAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: RESEND_API
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: BANCO_INTER_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: BANCO_INTER_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: BANCO_INTER_BASE_URL
    value: https://cdpj.partners.bancointer.com.br
  - key: BANCO_INTER_SCOPE
    value: "rec.read rec.write cob.write cob.read payloadlocationrec.write boleto-cobranca.read boleto-cobranca.write"
  - key: S3_ENDPOINT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: S3_REGION
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: S3_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: S3_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: S3_BUCKET_NAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: RABBITMQ_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET

